[package]
name = "bookmycomics-server"
version = "0.1.0"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0-rc"
actix-session = "0.1.0-rc"
json = "0.11"
futures = "0.1"
